### ISSUE TITLE
make layer_names optional

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-prevalence-predictor-spaMM#2]
At the moment I think this crashes if you omit `layer_names` from the request.

https://github.com/disarm-platform/fn-prevalence-predictor-spaMM/blob/e8bb4be17c0045812d50504caf09b38651e8495b/function/function.R#L20

**Comment by onlyjsmith** [comment]
Have added a couple of **temporary** checks in the function, while we debug.

https://github.com/disarm-platform/fn-prevalence-predictor-spaMM/commit/df9a84466ef6eb4117489e74d8e594241c4c2ce3

**Comment by HughSt** [comment]
I know why it doesn't work. Working on an updated function in `disarmr` which I can use to redeploy an updated version

**Comment by onlyjsmith** [comment]
Not developing function further
